#!/usr/bin/env python3
import sys

from clickhouse_driver import Client
from clickhouse_driver.errors import Error, LogicalError


def clickhouse_client_tty():
    client = Client("localhost")

    while True:
        query = input("[clickhouse1] :) ")

        if query.lower() in ["exit", "quit"]:
            sys.exit(0)

        try:
            result = client.execute(query)

            for row in result:
                print(row)

        except Error as e:
            error = "Exception:\n" + str(e)
            print(error)


if __name__ == "__main__":
    clickhouse_client_tty()
