version: '2.3'

services:
  minio1:
    image: minio/minio:RELEASE.2022-04-09T15-09-52Z
    volumes:
      - data1-1:/data1
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-}
    command: server --address :9001 /data1-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 2s
      timeout: 5s
      retries: 60
