FROM clickhouse/clickhouse-keeper:24.3

# keeper throws errors if this directory doesn't exist
RUN mkdir -p /var/lib/clickhouse-keeper && \
    chown clickhouse:clickhouse /var/lib/clickhouse-keeper
RUN mkdir -p /opt/cores
