version: '2.3'

services:
  keeper:
    build:
      context: .
      dockerfile: Dockerfile.keeper
    expose:
      - "2181"
    init: true
    environment:
      - KEEPER_SERVER_ID=1
    volumes:
      - "${CLICKHOUSE_TESTS_KEEPER_BIN_PATH:-${CLICKHOUSE_TESTS_SERVER_BIN_PATH:-/usr/bin/clickhouse}}:/usr/bin/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/configs/keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml"
    healthcheck:
      test: clickhouse-keeper client -q "stat"
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 2s