version: "2.3"

services:
  clickhouse:
    image: altinityinfra/clickhouse-regression-multiarch:1.0
    init: true
    expose:
      - "9000"
      - "9009"
      - "8123"
      - "2181"
      - "44444"
      - "9281"
      - "9010"
      - "8443"
      - "9444"
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.d/:/etc/clickhouse-server/config.d/"
      - "${CLICKHOUSE_TESTS_SERVER_BIN_PATH:-/usr/bin/clickhouse}:/usr/bin/clickhouse"
      - "${CLICKHOUSE_TESTS_ODBC_BRIDGE_BIN_PATH:-/usr/bin/clickhouse-odbc-bridge}:/usr/bin/clickhouse-odbc-bridge"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse-client/:/etc/clickhouse-client"
      - "${CLICKHOUSE_TESTS_DIR}/test_files/break-hash:/var/lib/break-hash"
      - "${CLICKHOUSE_TESTS_DIR}/test_files/https_app_file.py:/https_app_file.py"
      - "${CLICKHOUSE_TESTS_DIR}/test_files/http_app_file.py:/http_app_file.py"

    entrypoint: bash -c "tail -f /dev/null"
    healthcheck:
      test: echo 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 300s
    cap_add:
      - SYS_PTRACE
    security_opt:
      - label:disable
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4096M
        reservations:
          memory: 4096M
