version: '2.3'

services:
  zookeeper:
    image: zookeeper:3.4.12
    expose:
      - "2181"
      - "2281"
    environment:
      ZOO_TICK_TIME: 500
      ZOO_MY_ID: 4
      ZOO_SERVERS: server.4=localhost:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 2s
    security_opt:
      - label:disable
