name: 'Cache setup'
description: 'Cache setup'

runs:
  using: 'composite'
  steps:
    - name: Setup Docker cache
      shell: bash
      run: |
        echo "::group::Docker Caching"
        if ! systemctl is-active --quiet docker; then
            echo "Docker is not running, skipping Docker cache setup"
            echo "::endgroup::"
            exit 0
        fi

        if [ -d "/mnt/cache" ]; then
            DOCKER_CACHE_DIR="/mnt/cache/docker"
            echo "Using docker cache directory: $DOCKER_CACHE_DIR"

            # Ensure target cache directories exist
            sudo mkdir -p "$DOCKER_CACHE_DIR/image" "$DOCKER_CACHE_DIR/buildkit" "$DOCKER_CACHE_DIR/overlay2"
            sudo mkdir -p "/var/lib/docker/image" "/var/lib/docker/buildkit" "/var/lib/docker/overlay2"

            echo "Stopping Docker to prepare cache"
            sudo systemctl stop docker
            sudo sync

            echo "Copying buildkit from cache if exists"
            if [ -d "$DOCKER_CACHE_DIR/buildkit" ]; then
                sudo rm -rf /var/lib/docker/buildkit
                sudo cp -a "$DOCKER_CACHE_DIR/buildkit" /var/lib/docker/buildkit
            fi

            echo "Copying overlay2 from cache if exists"
            if [ -d "$DOCKER_CACHE_DIR/overlay2" ]; then
                sudo rm -rf /var/lib/docker/overlay2
                sudo cp -a "$DOCKER_CACHE_DIR/overlay2" /var/lib/docker/overlay2
            fi

            echo "Copying image from cache if exists"
            if [ -d "$DOCKER_CACHE_DIR/image" ]; then
                sudo rm -rf /var/lib/docker/image
                sudo cp -a "$DOCKER_CACHE_DIR/image" /var/lib/docker/image
            fi

            sudo systemctl start docker
        else
            echo "No docker cache directory available, proceeding without caching"
        fi
        echo "::endgroup::"

    - name: Setup Python cache
      shell: bash
      run: |
        echo "::group::Python venv caching"
        if [ -d "/mnt/cache" ]; then
            PYTHON_CACHE_DIR="/mnt/cache/python3.12-venv"
            mkdir -p "$PYTHON_CACHE_DIR" "$PWD/venv"
            sudo mount --bind "$PYTHON_CACHE_DIR" "$PWD/venv"
            echo "Using Python cached venv directory: $PYTHON_CACHE_DIR"
        else
            PYTHON_CACHE_DIR=""
            echo "No Python venv cache directory available, proceeding without caching"
        fi
        echo "::endgroup::"
