name: 'Cache Setup'
description: 'Setup caching for Python dependencies'

runs:
  using: 'composite'
  steps:
    - name: Cache Python venv
      uses: actions/cache@v4
      with:
        path: venv
        key: ${{ runner.os }}-${{ runner.arch }}-python-${{ hashFiles('.python-version') }}-venv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-python-${{ hashFiles('.python-version') }}-venv-
