version: '2.3'

services:
  clickhouse:
    image: registry.gitlab.com/altinity-public/container-images/test/clickhouse-functional-test:1.0
    init: true
    expose:
      - "9000" # remote
      - "8123" # http
      - "11111" # s3
      - "8443" # https
      - "9440" # tcp
      - "9181" # zookeeper
      - "9010" # tcp proxy
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/access_control.xml:/etc/clickhouse-server/config.d/access_control.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/keeper_port.xml:/etc/clickhouse-server/config.d/keeper_port.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/log_to_console.xml:/etc/clickhouse-server/config.d/log_to_console.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/logging_no_rotate.xml:/etc/clickhouse-server/config.d/logging_no_rotate.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/macros.xml:/etc/clickhouse-server/config.d/macros.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/more_clusters.xml:/etc/clickhouse-server/config.d/more_clusters.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/path.xml:/etc/clickhouse-server/config.d/path.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/query_masking_rules.xml:/etc/clickhouse-server/config.d/query_masking_rules.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/tcp_with_proxy.xml:/etc/clickhouse-server/config.d/tcp_with_proxy.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/test_cluster_with_incorrect_pw.xml:/etc/clickhouse-server/config.d/test_cluster_with_incorrect_pw.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/text_log.xml:/etc/clickhouse-server/config.d/text_log.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.d/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/users.d/access_management.xml:/etc/clickhouse-server/users.d/access_management.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/users.d/allow_introspection_functions.xml:/etc/clickhouse-server/users.d/allow_introspection_functions.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/users.d/allow_only_from_localhost.xml:/etc/clickhouse-server/users.d/allow_only_from_localhost.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/users.d/log_queries.xml:/etc/clickhouse-server/users.d/log_queries.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/users.d/readonly.xml:/etc/clickhouse-server/users.d/readonly.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/users.d/session_log_test.xml:/etc/clickhouse-server/users.d/session_log_test.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/config.xml:/etc/clickhouse-server/config.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/users.xml:/etc/clickhouse-server/users.xml"
      - "${CLICKHOUSE_TESTS_DIR}/../configs/clickhouse/embedded.xml:/etc/clickhouse-server/embedded.xml"
      - "${CLICKHOUSE_TESTS_SERVER_BIN_PATH:-/usr/bin/clickhouse}:/usr/bin/clickhouse"
      - "${CLICKHOUSE_TESTS_DIR}/wrappers/clickhouse-benchmark:/usr/bin/clickhouse-benchmark"
      - "${CLICKHOUSE_TESTS_DIR}/wrappers/clickhouse-client:/usr/bin/clickhouse-client"
      - "${CLICKHOUSE_TESTS_DIR}/wrappers/clickhouse-compressor:/usr/bin/clickhouse-compressor"
      - "${CLICKHOUSE_TESTS_DIR}/wrappers/clickhouse-extract-from-config:/usr/bin/clickhouse-extract-from-config"
      - "${CLICKHOUSE_TESTS_DIR}/wrappers/clickhouse-git-import:/usr/bin/clickhouse-git-import"
      - "${CLICKHOUSE_TESTS_DIR}/wrappers/clickhouse-local:/usr/bin/clickhouse-local"
      - "${CLICKHOUSE_TESTS_DIR}/wrappers/clickhouse-obfuscator:/usr/bin/clickhouse-obfuscator"
      - "${CLICKHOUSE_TESTS_DIR}/wrappers/clickhouse-server:/usr/bin/clickhouse-server"
      - "${CLICKHOUSE_TESTS_ODBC_BRIDGE_BIN_PATH:-/usr/bin/clickhouse-odbc-bridge}:/usr/bin/clickhouse-odbc-bridge"
      - "${CLICKHOUSE_TESTS_DIR}/src/:/functional/"
    entrypoint: bash -c "tail -f /dev/null"
    healthcheck:
      test: echo 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 300s
    cap_add:
      - SYS_PTRACE
    security_opt:
      - label:disable
