version: '2.3'

services:
  duckdb:
    image: altinityinfra/clickhouse-regression-multiarch:1.0
    init: true
    expose:
      - "9000"
      - "9009"
      - "8123"
    volumes:
      - "${DUCKDB_TESTS_BIN_PATH:-/usr/bin/duckdb}:/usr/bin/duckdb"
    entrypoint: bash -c "tail -f /dev/null"
    healthcheck:
      test: echo 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 300s
    cap_add:
      - SYS_PTRACE
    security_opt:
      - label:disable
