version: '2.3'

services:
  kafka:
    image: confluentinc/cp-kafka:5.2.0
    expose:
      - "9092"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=${CLICKHOUSE_TESTS_COORDINATOR}1:2181
      - ZOOKEEPER=${CLICKHOUSE_TESTS_COORDINATOR}1:2181
      - KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
    healthcheck:
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 2s
    security_opt:
        - label:disable
