version: '2.3'

services:
  zookeeper:
    image: zookeeper:${CLICKHOUSE_TESTS_ZOOKEEPER_VERSION:-3.8.4}
    expose:
      - "2181"
    environment:
      ZOO_TICK_TIME: 500
      ZOO_MY_ID: 1
      #ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      ZOO_4LW_COMMANDS_WHITELIST: "*"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 300s
    security_opt:
      - label:disable
