version: '2.3'

services:
  minio-client:
    image: minio/mc:RELEASE.2022-06-11T21-10-36Z
    entrypoint: >
     /bin/sh -c "
     /usr/bin/mc config host add minio http://minio:9001 minio minio123;
     /usr/bin/mc mb minio/root;

     /usr/bin/mc rm -r --force minio/warehouse;
     /usr/bin/mc mb minio/warehouse --ignore-existing;
     /usr/bin/mc policy set public minio/warehouse;

     touch /tmp/ready;
     "
    healthcheck:
      test: ["CMD-SHELL", "[ -f /tmp/ready ] && /usr/bin/mc ls minio/warehouse || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 60
