version: '2.3'

services:
  parquetify:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    entrypoint: tail -f /dev/null
    volumes:
        - "${CLICKHOUSE_TESTS_DIR}/data/json_files:/json_files"
