version: '2.3'

services:
  postgres:
    image: postgres:15.0-bullseye
    restart: always
    environment:
      POSTGRES_DB: 'default'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    expose:
      - '5432'
    healthcheck:
      test: PGPASSWORD=password psql -U user -d default -c "select 1;"
      interval: 3s
      timeout: 2s
      retries: 40
      start_period: 2s
