version: '2.3'

services:
  aws:
    image: registry.gitlab.com/altinity-public/container-images/s3-tools:2.0
    environment:
      - S3_AMAZON_KEY_ID=${S3_AMAZON_KEY_ID:-}
      - S3_AMAZON_ACCESS_KEY=${S3_AMAZON_ACCESS_KEY:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_REGION=${AWS_REGION:-}
    tty: true