version: '2.3'

services:
  clickhouse:
    image: registry.gitlab.com/altinity-public/container-images/test/clickhouse-intergration-test-pyarrow:2.0
    init: true
    expose:
      - "9000"
      - "9009"
      - "8123"
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.d/logs.xml:/etc/clickhouse-server/config.d/logs.xml"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.d/ports.xml:/etc/clickhouse-server/config.d/ports.xml"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.d/remote.xml:/etc/clickhouse-server/config.d/remote.xml"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.d/ssl.xml:/etc/clickhouse-server/config.d/ssl.xml"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.d/storage.xml:/etc/clickhouse-server/config.d/storage.xml"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.d/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml"
      - "${CLICKHOUSE_TESTS_DIR}/test_files/clickhouse_table_def.txt:/var/lib/clickhouse/user_files/clickhouse_table_def.txt"
      - "${CLICKHOUSE_TESTS_DIR}/test_files/data_NONE.Parquet:/var/lib/clickhouse/user_files/data_NONE.Parquet"
      - "${CLICKHOUSE_TESTS_DIR}/test_files/data_BROTLI.Parquet:/var/lib/clickhouse/user_files/data_BROTLI.Parquet.BROTLI"
      - "${CLICKHOUSE_TESTS_DIR}/test_files/data_GZIP.Parquet:/var/lib/clickhouse/user_files/data_GZIP.Parquet.GZIP"
      - "${CLICKHOUSE_TESTS_DIR}/test_files/data_SNAPPY.Parquet:/var/lib/clickhouse/user_files/data_SNAPPY.Parquet.SNAPPY"
      - "${CLICKHOUSE_TESTS_DIR}/test_files/data_ZSTD.Parquet:/var/lib/clickhouse/user_files/data_ZSTD.Parquet.ZSTD"
      - "${CLICKHOUSE_TESTS_DIR}/test_files/data_LZ4.Parquet:/var/lib/clickhouse/user_files/data_LZ4.Parquet.LZ4"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/ssl:/etc/clickhouse-server/ssl"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.xml:/etc/clickhouse-server/config.xml"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/users.xml:/etc/clickhouse-server/users.xml"
      - "${CLICKHOUSE_TESTS_SERVER_BIN_PATH:-/usr/bin/clickhouse}:/usr/bin/clickhouse"
      - "${CLICKHOUSE_TESTS_ODBC_BRIDGE_BIN_PATH:-/usr/bin/clickhouse-odbc-bridge}:/usr/bin/clickhouse-odbc-bridge"
    entrypoint: bash -c "tail -f /dev/null"
    healthcheck:
      test: echo 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 300s
    cap_add:
      - SYS_PTRACE
    security_opt:
      - label:disable