version: '2.3'

services:
  minio-client:
    image: minio/mc:RELEASE.2022-05-09T04-08-26Z
    entrypoint: >
     /bin/sh -c "
     /usr/bin/mc config host add minio http://minio1:9001 minio minio123;
     /usr/bin/mc mb minio/root;
     touch /tmp/ready;
     "
    healthcheck:
      test: ["CMD", "ls", "/tmp/ready"]
      interval: 5s
      timeout: 2s
      retries: 60
