"""Reusable steps for dedicated CAS tests.

Modules
-------
disk         CAS disk / policy SETTINGS clauses
tables       MergeTree / ReplicatedMergeTree / Distributed create helpers
data         Insert helpers
checksums    Partition and table checksums
replication  SYNC REPLICA, fetch pause/resume, replica agreement
partitions   ALTER PARTITION / FETCH helpers
metrics      CAS system.events snapshots for relink proofs
freeze       FREEZE / UNFREEZE helpers
gc           SYSTEM CAS GC RUN helpers
pool         direct inspection of the objects a CAS pool holds
"""

from cas.tests.steps.disk import (
    CAS_POLICY,
    CAS_POLICY_POOL,
    REPLICATED_CLUSTER,
    SHARDED_CLUSTER,
    cas_disk_clause,
    cas_policy_clause,
    storage_settings,
)
from cas.tests.steps.alter import (
    ALTER_COLUMNS,
    add_column,
    add_constraint,
    add_enum_values,
    add_index,
    add_projection,
    add_statistics,
    alter_delete,
    alter_update,
    clear_column_in_partition,
    clear_index,
    clear_projection,
    clear_statistics,
    column_metadata,
    comment_column,
    create_filled_alter_table,
    drop_column,
    drop_constraint,
    drop_index,
    drop_projection,
    drop_statistics,
    insert_alter_rows,
    materialize_column,
    materialize_index,
    materialize_projection,
    materialize_statistics,
    materialize_ttl,
    modify_column,
    modify_column_setting,
    modify_constraint,
    modify_order_by,
    modify_sample_by,
    modify_statistics,
    modify_ttl,
    remove_column_property,
    remove_sample_by,
    remove_ttl,
    rename_column,
    reset_column_setting,
    show_create_table,
    table_columns,
)
from cas.tests.steps.checksums import (
    partition_checksum,
    payload_table_checksum,
    table_checksum,
    table_row_count,
)
from cas.tests.steps.data import (
    insert_cas_partitions,
    insert_cas_payload_rows,
)
from cas.tests.steps.freeze import (
    freeze_table,
    local_backup_files,
    unfreeze_table,
)
from cas.tests.steps.gc import (
    collect_garbage,
    start_garbage_collection,
    stop_garbage_collection,
)
from cas.tests.steps.pool import (
    backup_manifest_keys,
    blob_keys,
    cleanup_cas_storage,
    delete_pool_prefix,
    namespaces_of,
    pool_difference,
    pool_size_bytes,
    pool_snapshot,
    settled_pool_snapshot,
    size_in_bytes,
)
from cas.tests.steps.metrics import (
    CAS_CURRENT_METRICS,
    CAS_PROFILE_EVENTS,
    INSERT_PROFILE_EVENTS,
    assert_blob_bodies_were_uploaded,
    assert_no_blob_reupload_on_fetch,
    blob_body_puts,
    blob_puts_avoided_or_deduped,
    cas_current_metrics,
    cas_event,
    cas_event_grew,
    cas_event_unchanged,
    cas_gauge,
    cas_events_delta,
    cas_events_snapshot,
    cas_metrics,
)
from cas.tests.steps.partitions import (
    active_part_names,
    attach_partition,
    attach_partition_from,
    detach_partition,
    drop_detached_partition,
    drop_partition,
    fetch_part,
    fetch_partition,
    forget_partition,
    move_partition_to_table,
    optimize_final,
    replace_partition_from,
)
from cas.tests.steps.replication import (
    assert_replicas_agree,
    assert_replication_queue_healthy,
    start_fetches,
    stop_fetches,
    sync_replica,
    sync_replicas,
)
from cas.tests.steps.tables import (
    active_part_disk,
    create_cas_merge_tree_table,
    table_engine_and_policy,
    create_distributed_over_cas,
    create_replicated_cas_table,
    create_replicated_cas_table_cross_pool,
    create_replicated_cas_table_on_cluster,
    create_replicated_local_table,
    create_sharded_local_cas_tables,
    insert_into_distributed,
)

__all__ = [
    "ALTER_COLUMNS",
    "CAS_POLICY",
    "CAS_POLICY_POOL",
    "REPLICATED_CLUSTER",
    "SHARDED_CLUSTER",
    "active_part_disk",
    "active_part_names",
    "add_column",
    "add_constraint",
    "add_enum_values",
    "add_index",
    "add_projection",
    "add_statistics",
    "alter_delete",
    "alter_update",
    "backup_manifest_keys",
    "blob_keys",
    "CAS_CURRENT_METRICS",
    "CAS_PROFILE_EVENTS",
    "INSERT_PROFILE_EVENTS",
    "assert_blob_bodies_were_uploaded",
    "assert_no_blob_reupload_on_fetch",
    "assert_replicas_agree",
    "assert_replication_queue_healthy",
    "attach_partition",
    "attach_partition_from",
    "blob_body_puts",
    "blob_puts_avoided_or_deduped",
    "cas_current_metrics",
    "cas_disk_clause",
    "cas_event",
    "cas_event_grew",
    "cas_event_unchanged",
    "cas_gauge",
    "cas_events_delta",
    "cas_events_snapshot",
    "cas_metrics",
    "cas_policy_clause",
    "clear_column_in_partition",
    "clear_index",
    "clear_projection",
    "clear_statistics",
    "collect_garbage",
    "start_garbage_collection",
    "stop_garbage_collection",
    "column_metadata",
    "comment_column",
    "create_cas_merge_tree_table",
    "create_distributed_over_cas",
    "create_filled_alter_table",
    "create_replicated_cas_table",
    "create_replicated_cas_table_cross_pool",
    "create_replicated_cas_table_on_cluster",
    "create_replicated_local_table",
    "create_sharded_local_cas_tables",
    "detach_partition",
    "drop_column",
    "drop_constraint",
    "drop_detached_partition",
    "drop_index",
    "drop_partition",
    "drop_projection",
    "drop_statistics",
    "fetch_part",
    "fetch_partition",
    "forget_partition",
    "freeze_table",
    "insert_cas_partitions",
    "insert_alter_rows",
    "insert_cas_payload_rows",
    "insert_into_distributed",
    "local_backup_files",
    "materialize_column",
    "materialize_index",
    "materialize_projection",
    "materialize_statistics",
    "materialize_ttl",
    "modify_column",
    "modify_column_setting",
    "modify_constraint",
    "modify_order_by",
    "modify_sample_by",
    "modify_statistics",
    "modify_ttl",
    "move_partition_to_table",
    "optimize_final",
    "partition_checksum",
    "payload_table_checksum",
    "cleanup_cas_storage",
    "delete_pool_prefix",
    "namespaces_of",
    "pool_difference",
    "pool_size_bytes",
    "pool_snapshot",
    "settled_pool_snapshot",
    "size_in_bytes",
    "replace_partition_from",
    "remove_column_property",
    "remove_sample_by",
    "remove_ttl",
    "rename_column",
    "reset_column_setting",
    "start_fetches",
    "stop_fetches",
    "storage_settings",
    "show_create_table",
    "table_columns",
    "sync_replica",
    "sync_replicas",
    "table_checksum",
    "table_engine_and_policy",
    "table_row_count",
    "unfreeze_table",
]
