version: "3.7"

services:

  keeper-1:
    extends:
      file: ../../docker-compose/keeper-service.yml
      service: keeper
    container_name: keeper-1
    hostname: keeper-1
    init: true
    ports:
      - "19181:9181"
      - "19234:9234"
      - "19182:9182"
    environment:
      - KEEPER_SERVER_ID=1
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-1/logs/:/var/log/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-1/data/:/var/lib/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/configs/keeper/config:/etc/clickhouse-keeper-configs/"
    entrypoint: ["tail", "-f", "/dev/null"] 
  
  keeper-2:
    extends:
      file: ../../docker-compose/keeper-service.yml
      service: keeper
    container_name: keeper-2
    hostname: keeper-2
    init: true
    ports:
      - "29181:9181"
      - "29234:9234"
      - "29182:9182"
    environment:
      - KEEPER_SERVER_ID=2
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-2/logs/:/var/log/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-2/data/:/var/lib/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/configs/keeper/config:/etc/clickhouse-keeper-configs/"
    entrypoint: ["tail", "-f", "/dev/null"] 

  keeper-3:
    extends:
      file: ../../docker-compose/keeper-service.yml
      service: keeper
    container_name: keeper-3
    hostname: keeper-3
    init: true
    ports:
      - "39181:9181"
      - "39234:9234"
      - "39182:9182"
    environment:
      - KEEPER_SERVER_ID=3
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-3/logs/:/var/log/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-3/data/:/var/lib/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/configs/keeper/config:/etc/clickhouse-keeper-configs/"
    entrypoint: ["tail", "-f", "/dev/null"] 

  keeper-4:
    extends:
      file: ../../docker-compose/keeper-service.yml
      service: keeper
    container_name: keeper-4
    hostname: keeper-4
    init: true
    ports:
      - "49181:9181"
      - "49234:9234"
      - "49182:9182"
    environment:
      - KEEPER_SERVER_ID=4
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-4/logs/:/var/log/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-4/data/:/var/lib/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/configs/keeper/config:/etc/clickhouse-keeper-configs/"
    entrypoint: ["tail", "-f", "/dev/null"] 
  
  keeper-5:
    extends:
      file: ../../docker-compose/keeper-service.yml
      service: keeper
    container_name: keeper-5
    hostname: keeper-5
    init: true
    ports:
      - "58181:9181"
      - "58234:9234"
      - "58182:9182"
    environment:
      - KEEPER_SERVER_ID=5
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-5/logs/:/var/log/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-5/data/:/var/lib/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/configs/keeper/config:/etc/clickhouse-keeper-configs/"
    entrypoint: ["tail", "-f", "/dev/null"] 

  keeper-6:
    extends:
      file: ../../docker-compose/keeper-service.yml
      service: keeper
    container_name: keeper-6
    hostname: keeper-6
    init: true
    ports:
      - "59181:9181"
      - "59234:9234"
      - "59182:9182"
    environment:
      - KEEPER_SERVER_ID=6
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-6/logs/:/var/log/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/keeper-6/data/:/var/lib/clickhouse-keeper"
      - "${CLICKHOUSE_TESTS_DIR}/configs/keeper/config:/etc/clickhouse-keeper-configs/"
    entrypoint: ["tail", "-f", "/dev/null"] 
