version: "2.3"

services:
  zookeeper:
    image: clickhouse-regression/zookeeper-node:${CLICKHOUSE_TESTS_ZOOKEEPER_VERSION:-3.8.4}
    pull_policy: never
    build:
      context: .
      dockerfile: zookeeper-node.Dockerfile
      args:
        ZOOKEEPER_VERSION: ${CLICKHOUSE_TESTS_ZOOKEEPER_VERSION:-3.8.4}
    expose:
      - "2181"
    init: true
    environment:
      ZOO_TICK_TIME: 500
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    command: tail -f /dev/null
    healthcheck:
      test: echo 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 300s
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable

  zookeeper-alone:
    extends: zookeeper
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 0
      ZOO_SERVERS: server.0=localhost:2888:3888;2181

  zookeeper1:
    extends: zookeeper
    hostname: zookeeper1
    environment:
      ZOO_MY_ID: 1
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/zookeeper1/data/:/data/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/zookeeper1/datalog/:/datalog"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/zookeeper1/logs/:/logs/"

  zookeeper2:
    extends: zookeeper
    hostname: zookeeper2
    environment:
      ZOO_MY_ID: 2
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/zookeeper2/data/:/data/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/zookeeper2/datalog/:/datalog/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/zookeeper2/logs/:/logs/"

  zookeeper3:
    extends: zookeeper
    hostname: zookeeper3
    environment:
      ZOO_MY_ID: 3
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/zookeeper3/data/:/data/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/zookeeper3/datalog/:/datalog/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/zookeeper3/logs/:/logs/"
