version: '2.3'

volumes:
  data1-1:

  clickhouse1_jbod1:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse1_jbod2:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse1_jbod3:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse1_jbod4:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse1_external:
    driver: local
    driver_opts:
      o: "size=200m"
      device: tmpfs
      type: tmpfs

  clickhouse1_external2:
    driver: local
    driver_opts:
      o: "size=200m"
      device: tmpfs
      type: tmpfs

  clickhouse2_jbod1:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse2_jbod2:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse2_jbod3:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse2_jbod4:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse2_external:
    driver: local
    driver_opts:
      o: "size=200m"
      device: tmpfs
      type: tmpfs

  clickhouse2_external2:
    driver: local
    driver_opts:
      o: "size=200m"
      device: tmpfs
      type: tmpfs

  clickhouse3_jbod1:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse3_jbod2:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse3_jbod3:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse3_jbod4:
    driver: local
    driver_opts:
      o: "size=40m"
      device: tmpfs
      type: tmpfs

  clickhouse3_external:
    driver: local
    driver_opts:
      o: "size=200m"
      device: tmpfs
      type: tmpfs

  clickhouse3_external2:
    driver: local
    driver_opts:
      o: "size=200m"
      device: tmpfs
      type: tmpfs

services:
  minio:
    extends:
      file: minio-service.yml
      service: minio

  minio-client:
    extends:
      file: minio-client.yml
      service: minio-client
    depends_on:
      minio:
        condition: service_healthy

  zookeeper1:
    extends:
      file: ../../helpers/docker/zookeeper-service.yml
      service: zookeeper1
    volumes:
      - clickhouse1_jbod1:/clickhouse1_jbod1
      - clickhouse1_jbod2:/clickhouse1_jbod2
      - clickhouse1_jbod3:/clickhouse1_jbod3
      - clickhouse1_jbod4:/clickhouse1_jbod4
      - clickhouse1_external:/clickhouse1_external
      - clickhouse1_external2:/clickhouse1_external2
      - clickhouse2_jbod1:/clickhouse2_jbod1
      - clickhouse2_jbod2:/clickhouse2_jbod2
      - clickhouse2_jbod3:/clickhouse2_jbod3
      - clickhouse2_jbod4:/clickhouse2_jbod4
      - clickhouse2_external:/clickhouse2_external
      - clickhouse2_external2:/clickhouse2_external2
      - clickhouse3_jbod1:/clickhouse3_jbod1
      - clickhouse3_jbod2:/clickhouse3_jbod2
      - clickhouse3_jbod3:/clickhouse3_jbod3
      - clickhouse3_jbod4:/clickhouse3_jbod4
      - clickhouse3_external:/clickhouse3_external
      - clickhouse3_external2:/clickhouse3_external2

  zookeeper2:
    extends:
      file: ../../helpers/docker/zookeeper-service.yml
      service: zookeeper2

  zookeeper3:
    extends:
      file: ../../helpers/docker/zookeeper-service.yml
      service: zookeeper3

  keeper1:
    extends:
      file: ../../helpers/docker/keeper-service.yml
      service: keeper1

  keeper2:
    extends:
      file: ../../helpers/docker/keeper-service.yml
      service: keeper2

  keeper3:
    extends:
      file: ../../helpers/docker/keeper-service.yml
      service: keeper3

  clickhouse1:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse1
    volumes:
      - clickhouse1_jbod1:/jbod1
      - clickhouse1_jbod2:/jbod2
      - clickhouse1_jbod3:/jbod3
      - clickhouse1_jbod4:/jbod4
      - clickhouse1_external:/external
      - clickhouse1_external2:/external2
      - ${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse1/database/:/var/lib/clickhouse/
      - ${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse1/logs/:/var/log/clickhouse-server/
      - ${CLICKHOUSE_TESTS_DIR}/configs/clickhouse1/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    depends_on:
      zookeeper1:
        condition: service_healthy
      minio:
        condition: service_healthy

  clickhouse2:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse2
    volumes:
      - clickhouse2_jbod1:/jbod1
      - clickhouse2_jbod2:/jbod2
      - clickhouse2_jbod3:/jbod3
      - clickhouse2_jbod4:/jbod4
      - clickhouse2_external:/external
      - clickhouse2_external2:/external2
      - ${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse2/database/:/var/lib/clickhouse/
      - ${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse2/logs/:/var/log/clickhouse-server/
      - ${CLICKHOUSE_TESTS_DIR}/configs/clickhouse2/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    depends_on:
      zookeeper1:
        condition: service_healthy
      minio:
        condition: service_healthy

  clickhouse3:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse3
    volumes:
      - clickhouse3_jbod1:/jbod1
      - clickhouse3_jbod2:/jbod2
      - clickhouse3_jbod3:/jbod3
      - clickhouse3_jbod4:/jbod4
      - clickhouse3_external:/external
      - clickhouse3_external2:/external2
      - ${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse3/database/:/var/lib/clickhouse/
      - ${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse3/logs/:/var/log/clickhouse-server/
      - ${CLICKHOUSE_TESTS_DIR}/configs/clickhouse3/macros.xml:/etc/clickhouse-server/config.d/macros.xml
    depends_on:
      zookeeper1:
        condition: service_healthy
      minio:
        condition: service_healthy

  all_services_ready:
    image: hello-world
    depends_on:
      clickhouse1:
        condition: service_healthy
      clickhouse2:
        condition: service_healthy
      clickhouse3:
        condition: service_healthy
      zookeeper1:
        condition: service_healthy
      zookeeper2:
        condition: service_healthy
      zookeeper3:
        condition: service_healthy
      keeper1:
        condition: service_healthy
      keeper2:
        condition: service_healthy
      keeper3:
        condition: service_healthy
      minio:
        condition: service_healthy
