version: '2.3'

services:
  clickhouse:
    build:
      context: .
      dockerfile: Dockerfile.clickhouse
    expose:
      - "9000"
      - "9009"
      - "8123"
    environment:
      - COORDINATOR_HOST_1=${CLICKHOUSE_TESTS_COORDINATOR}1
      - COORDINATOR_HOST_2=${CLICKHOUSE_TESTS_COORDINATOR}2
      - COORDINATOR_HOST_3=${CLICKHOUSE_TESTS_COORDINATOR}3
    volumes:
      - "${CLICKHOUSE_TESTS_SERVER_BIN_PATH:-/usr/bin/clickhouse}:/usr/bin/clickhouse"
      - "${CLICKHOUSE_TESTS_ODBC_BRIDGE_BIN_PATH:-/usr/bin/clickhouse-odbc-bridge}:/usr/bin/clickhouse-odbc-bridge"
    entrypoint: tail -f /dev/null
    healthcheck:
      test: echo 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 300s
    cap_add:
      - SYS_PTRACE
    security_opt:
      - label:disable
