version: '2.3'

services:
  clickhouse1:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse1
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse1/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse1/logs/:/var/log/clickhouse-server/"

  clickhouse2:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse2
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse2/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse2/logs/:/var/log/clickhouse-server/"

  clickhouse3:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse3
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse3/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse3/logs/:/var/log/clickhouse-server/"
  
  clickhouse4:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse4
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse4/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse4/logs/:/var/log/clickhouse-server/"
  
  clickhouse5:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse5
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse5/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse5/logs/:/var/log/clickhouse-server/"
  
  clickhouse6:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse6
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse6/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse6/logs/:/var/log/clickhouse-server/"
  
  clickhouse7:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse7
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse7/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse7/logs/:/var/log/clickhouse-server/"
    
  clickhouse8:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse8
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse8/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse8/logs/:/var/log/clickhouse-server/"

  clickhouse9:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse9
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse9/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse9/logs/:/var/log/clickhouse-server/"
    
  clickhouse10:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse10
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse10/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse10/logs/:/var/log/clickhouse-server/"

  # dummy service which does nothing, but allows to postpone
  # 'docker-compose up -d' till all dependencies will go healthy
  all_services_ready:
    image: hello-world
    depends_on:
      clickhouse1:
        condition: service_healthy
      clickhouse2:
        condition: service_healthy
      clickhouse3:
        condition: service_healthy
      clickhouse4:
        condition: service_healthy
      clickhouse5:
        condition: service_healthy
      clickhouse6:
        condition: service_healthy
      clickhouse7:
        condition: service_healthy
      clickhouse8:
        condition: service_healthy
      clickhouse9:
        condition: service_healthy
      clickhouse10:
        condition: service_healthy

