name: 'Cache sync'
description: 'Cache sync'

runs:
  using: 'composite'
  steps:
    - name: Sync Docker cache
      shell: bash
      run: |
        echo "::group::Sync Docker cache"
        if [ -d "/mnt/cache" ]; then
          echo "Stopping containers and cleaning up..."
          sudo docker stop $(sudo docker ps -q) || true
          sudo docker rm -fv $(sudo docker ps -a -q) || true
          sync
          sudo systemctl stop docker

          echo "Copying overlay2 and image to /mnt/cache/docker..."
          sudo mkdir -p /mnt/cache/docker /var/lib/docker/overlay2
          sudo cp -a /var/lib/docker/overlay2 /mnt/cache/docker/overlay2
        else
          echo "/mnt/cache not available — skipping Docker cache sync"
        fi
        echo "::endgroup::"
        