name: 'Cache sync'
description: 'Cache sync'

runs:
  using: 'composite'
  steps:
    - name: Sync Docker cache
      shell: bash
      run: |
        if ! command -v docker >/dev/null; then
            echo "Docker is not installed, skipping cache sync"
            exit 0
        fi

        if [ -d "/mnt/cache" ]; then
            DOCKER_CACHE_DIR="/mnt/cache/docker"

            echo "Stopping containers and cleaning up..."
            sudo docker stop $(sudo docker ps -q) || true
            sudo docker rm -fv $(sudo docker ps -a -q) || true

            echo "Stopping Docker daemon"
            sudo systemctl stop docker
            sudo sync

            echo "Syncing docker folders to cache"           
            for DIR in overlay2 image buildkit; do
                if [ -d "/var/lib/docker/$DIR" ]; then
                    sudo mkdir -p "$DOCKER_CACHE_DIR/$DIR"
                    shopt -s nullglob
                    for target in /var/lib/docker/$DIR/*; do
                        id=$(basename "$target")
                        if [ ! -L "$target" ]; then
                            sudo rsync -aH --delete "/var/lib/docker/$DIR/$id" "$DOCKER_CACHE_DIR/$DIR/$id"
                        fi
                    done
                    shopt -u nullglob
                fi
            done
            sudo sync
        else
            echo "/mnt/cache not available — skipping Docker cache sync"
        fi
        
