name: 'Cache sync'
description: 'Cache sync'

runs:
  using: 'composite'
  steps:
    - name: Sync Docker cache
      shell: bash
      run: |
        if ! command -v docker >/dev/null; then
            echo "Docker is not installed, skipping cache sync"
            exit 0
        fi

        if [ -d "/mnt/cache" ]; then
            echo "Stopping containers and cleaning up..."
            sudo docker stop $(sudo docker ps -q) || true
            sudo docker rm -fv $(sudo docker ps -a -q) || true

            echo "Stopping Docker daemon"
            sudo systemctl stop docker
            sudo sync

            echo "Syncing docker folders to cache"
            sudo mkdir -p /mnt/cache/docker

            echo "Unmounting docker cache mounts"
            if [ -f /etc/docker-cache-mounts ]; then
                echo "Unmounting $(cat /etc/docker-cache-mounts)"
                sudo xargs -a /etc/docker-cache-mounts -r umount || true
            fi

            for DIR in overlay2 image buildkit; do
                sudo rsync -aH --delete /var/lib/docker/$DIR/ /mnt/cache/docker/$DIR/
            done
            sudo sync
        else
            echo "/mnt/cache not available — skipping Docker cache sync"
        fi
        
