name: 'Cache sync'
description: 'Cache sync'

runs:
  using: 'composite'
  steps:
    - name: Sync Docker cache
      shell: bash
      run: |
        if ! command -v docker >/dev/null; then
            echo "Docker is not installed, skipping cache sync"
            exit 0
        fi

        if [ -d "/mnt/cache" ]; then
            DOCKER_CACHE_DIR="/mnt/cache/docker"

            echo "Stopping containers and cleaning up..."
            sudo docker stop $(sudo docker ps -q) || true
            sudo docker rm -fv $(sudo docker ps -a -q) || true

            echo "Stopping Docker daemon"
            sudo systemctl stop docker
            sudo sync

            echo "Syncing docker folders to cache"           
            for DIR in overlay2 image buildkit; do
                if sudo test -d "/var/lib/docker/$DIR"; then
                    echo "Syncing /var/lib/docker/$DIR"
                    sudo mkdir -p "$DOCKER_CACHE_DIR/$DIR"
                    targets=$(sudo find "/var/lib/docker/$DIR" -mindepth 1 -maxdepth 1)
                    if [ -z "$targets" ]; then
                        echo "⚠️  No entries found in /var/lib/docker/$DIR — skipping"
                        continue
                    fi
                    for target in $targets; do
                        id=$(basename "$target")
                        if sudo test ! -L "$target"; then
                            echo "Syncing $target to $DOCKER_CACHE_DIR/$DIR/$id"
                            if sudo test -d "$target"; then
                                sudo rsync -aH --delete "$target/" "$DOCKER_CACHE_DIR/$DIR/$id"
                            else
                                sudo rsync -aH "$target" "$DOCKER_CACHE_DIR/$DIR/$id"
                            fi
                        fi
                    done
                fi
            done
            sudo sync
        else
            echo "/mnt/cache not available — skipping Docker cache sync"
        fi
        
