services:
  keycloak:
    image: keycloak/keycloak:26.3
    command: start-dev --import-realm --hostname=localhost
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "sh", "-c", "exec 3<>/dev/tcp/localhost/8080"]
      interval: 5s
      timeout: 30s
      retries: 20

  clickhouse1:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse1
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse1/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse1/logs/:/var/log/clickhouse-server/"
    mem_limit: 4000M
    cpus: 2.0
    depends_on:
      keycloak:
        condition: service_healthy

#  clickhouse:
#    image: altinityinfra/clickhouse-server:920-25.6.2.28000.altinityantalya
#    ports:
#      - "8123:8123"
#    volumes:
#      # - clickhouse-data:/var/lib/clickhouse
#      - ./clickhouse/clickhouse-low-ram-config.xml:/etc/clickhouse-server/config.d/clickhouse-low-ram-config.xml:ro
#      - ./clickhouse/clickhouse-low-ram-user-profile.xml:/etc/clickhouse-server/users.d/clickhouse-low-ram-user-profile.xml:ro
#      - ./clickhouse/startup_scripts.xml:/etc/clickhouse-server/config.d/startup_scripts.xml:ro
#      - ./clickhouse/processor_directory.xml:/etc/clickhouse-server/config.d/processor_directory.xml:ro
#    mem_limit: 4000M
#    cpus: 2.0
#    depends_on:
#      keycloak:
#        condition: service_healthy

  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana:12.0.2}
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Keycloak
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana-client
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=grafana-secret
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=http://localhost:8080/realms/grafana/protocol/openid-connect/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=http://keycloak:8080/realms/grafana/protocol/openid-connect/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=http://keycloak:8080/realms/grafana/protocol/openid-connect/userinfo
      # - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(groups[*], 'grafana-admins') && 'Admin' || 'Viewer'
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource
      - GF_INSTALL_PLUGINS=https://github.com/Altinity/clickhouse-grafana/releases/download/v3.3.0/vertamedia-clickhouse-datasource-3.3.0.zip;vertamedia-clickhouse-datasource
    ports:
      - "3000:3000"
    # volumes:
    #   - grafana-data:/var/lib/grafana
    depends_on:
      keycloak:
        condition: service_healthy

# volumes:
#   grafana-data:
#   clickhouse-data:
