version: '2.3'

services:

  kerberos:
    extends:
      file: kerberos-service.yml
      service: kerberos
    hostname: kerberos
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/share:/share"

  clickhouse1:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse1
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse1/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse1/logs/:/var/log/clickhouse-server/"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse1/config.d:/etc/clickhouse-server/config.d"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse1/users.d:/etc/clickhouse-server/users.d"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/share:/share"

  clickhouse2:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse2
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse2/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse2/logs/:/var/log/clickhouse-server/"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse2/config.d:/etc/clickhouse-server/config.d"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse2/users.d:/etc/clickhouse-server/users.d"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/share:/share"

  clickhouse3:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    hostname: clickhouse3
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse3/database/:/var/lib/clickhouse/"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/clickhouse3/logs/:/var/log/clickhouse-server/"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse3/config.d:/etc/clickhouse-server/config.d"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse3/users.d:/etc/clickhouse-server/users.d"
      - "${CLICKHOUSE_TESTS_DIR}/_instances/share:/share"

  bash-tools:
    extends:
      file: ../../docker-compose/bash-tools.yml
      service: bash-tools
    hostname: bash-tools
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/share:/share"
      - "${CLICKHOUSE_TESTS_DIR}/configs/kerberos/etc/krb5.conf:/etc/krb5.conf"
    environment:
      KRB5_CLIENT_KTNAME: /etc/krb5.keytab
      KRB5_KTNAME: /etc/krb5.keytab
      KRB5CCNAME: /tmp/krb5cc_0
  
  bash-tools-2:
    extends:
      file: ../../docker-compose/bash-tools.yml
      service: bash-tools
    hostname: bash-tools
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/_instances/share:/share"
      - "${CLICKHOUSE_TESTS_DIR}/configs/kerberos/etc/krb5.conf:/etc/krb5.conf"
    environment:
      KRB5_CLIENT_KTNAME: /etc/krb5.keytab
      KRB5_KTNAME: /etc/krb5.keytab
      KRB5CCNAME: /tmp/krb5cc_0

  # dummy service which does nothing, but allows to postpone
  # 'docker-compose up -d' till all dependencies will go healthy
  all_services_ready:
    image: hello-world
    depends_on:
      clickhouse1:
        condition: service_healthy
      clickhouse2:
        condition: service_healthy
      clickhouse3:
        condition: service_healthy

networks:
  default:
    name: krbnet
    driver: bridge
