version: '2.3'

services:
  clickhouse:
    image: registry.gitlab.com/altinity-public/container-images/test/clickhouse-integration-test:21.12
    init: true
    expose:
      - "9000"
      - "9009"
      - "8123"
      - "2181"
      - "44444"
    volumes:
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.xml:/etc/clickhouse-server/config.xml"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/users.xml:/etc/clickhouse-server/users.xml"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.d/dhparam.pem:/etc/clickhouse-server/config.d/dhparam.pem"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.d/server.crt:/etc/clickhouse-server/config.d/server.crt"
      - "${CLICKHOUSE_TESTS_DIR}/configs/clickhouse/config.d/server.key:/etc/clickhouse-server/config.d/server.key"
      - "${CLICKHOUSE_TESTS_SERVER_BIN_PATH:-/usr/bin/clickhouse}:/usr/bin/clickhouse"
      - "${CLICKHOUSE_TESTS_ODBC_BRIDGE_BIN_PATH:-/usr/bin/clickhouse-odbc-bridge}:/usr/bin/clickhouse-odbc-bridge"
    entrypoint: bash -c "tail -f /dev/null"
    healthcheck:
      test: echo 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 300s
    cap_add:
      - SYS_PTRACE
    security_opt:
      - label:disable
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
        reservations:
          memory: 4096M
