version: '2.3'

services:
  zookeeper:
    image: zookeeper:3.8.4
    restart: always
    expose:
      - "2181"
      - "2281"
    environment:
      ZOO_TICK_TIME: 1000
      ZOO_SYNC_LIMIT: 4
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 300s
    security_opt:
      - label:disable
