version: '2.3'

services:
  minio:
    image: minio/minio
    # volumes:
    #   - data1-1:/data1
    networks:
      default:
        aliases:
          - warehouse.minio
    ports:
      - "9001:9001"
      - "9002:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 2s
      timeout: 5s
      retries: 60
