version: '2.3'

services:
  mysql:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_DATABASE: 'default'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    healthcheck:
      test: mysql -D default -u user --password=password -e "select 1;"
      interval: 3s
      timeout: 2s
      retries: 40
      start_period: 2s
