name: Run CI/CD regression tests
run-name: ${{ github.actor }} is running regression tests
on: 
  workflow_dispatch:
    inputs:
      package:
        description: "Package either 'docker://' or 'https://'. Example: 'https://s3.amazonaws.com/clickhouse-builds/23.3/.../package_release/clickhouse-common-static_23.3.1.64_amd64.deb', or 'docker://clickhouse/clickhouse-server:22.11.6-alpine'"
        required: true
        type: string
        default: docker://clickhouse/clickhouse-server
      version:
        description: "Expected version. Example: 23.3.1.64"
        required: true
        type: string
        default: 23.2.2.20
      suite:
        description: "Test suite to run (default: all)"
        type: choice
        options:
          - all
          - aes_encryption
          - aggregate_functions
          - atomic_insert
          - base_58
          - clickhouse_keeper
          - datetime64_extended_range
          - disk_level_encryption
          - dns
          - example
          - extended_precision_data_types
          - functional
          - kafka
          - kerberos
          - ldap
          - lightweight_delete
          - map_type
          - parquet
          - part_moves_between_shards
          - rbac
          - s3
          - s3_aws
          - s3_gcs
          - selects
          - ssl_server
          - tiered_storage
          - tiered_storage_aws
          - tiered_storage_gcs
          - window_functions
          - benchmark
      artifacts:
        description: "Artifact S3 bucket"
        type: choice
        options:
          - internal
          - public

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_REPORT_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_REPORT_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REPORT_REGION }}
  PYTHONIOENCODING: utf-8
  clickhouse_binary_path: ${{ inputs.package }}
  version: ${{ inputs.version }}
  artifacts: ${{ inputs.artifacts }}

jobs:
  aes_encryption:
    runs-on: self-hosted
    env:
      SUITE: aes_encryption
    if: ${{ inputs.suite == 'all' || inputs.suite == 'aes_encryption' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: .github/setup.sh

      - name: Run ${{ env.SUITE }} suite
        run: python3 
              -u ${{ env.SUITE }}/regression.py
              --test-to-end
              --local
              --collect-service-logs 
              --output ${{ vars.OUTPUT }} 
              --parallel ${{ vars.PARALLEL }}
              --clickhouse-binary-path ${{ env.clickhouse_binary_path }}  
              --clickhouse-version ${{ env.version }} 
              --attr project="$GITHUB_REPOSITORY" project.id="$GITHUB_REPOSITORY_ID" user.name="$GITHUB_ACTOR" version="${{ inputs.version }}" package="${{ inputs.package }}" repository="https://github.com/Altinity/clickhouse-regression" commit.hash="$GITHUB_SHA" job.id="$GITHUB_RUN_ID" job.url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" arch="${{ vars.ARCH }}"
              --log raw.log

      - name: Create and upload logs
        if: success() || failure()
        run: .github/manage_logs.sh ${{ vars.UPLOAD_LOGS }}

      - name: Debug pause
        if: ${{ vars.PAUSE == 1 }}
        run: |
          echo "...debugging mode...sleeping 6 hours..."
          sleep 21600

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.SUITE }}-artifacts
          path: |
            ./report.html
            ./*.log.txt
            ./*.log
            ./*.html
            ./*/_instances/*/logs/*.log
            ./*/*/_instances/*/logs/*.log
            ./*/_instances/*.log
            ./*/*/_instances/*.log

  aggregate_functions:
    runs-on: self-hosted
    env:
      SUITE: aggregate_functions
    if: ${{ inputs.suite == 'all' || inputs.suite == 'aggregate_functions' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: .github/setup.sh

      - name: Run ${{ env.SUITE }} suite
        run: python3 
              -u ${{ env.SUITE }}/regression.py
              --test-to-end
              --local
              --collect-service-logs 
              --output ${{ vars.OUTPUT }} 
              --parallel ${{ vars.PARALLEL }}
              --clickhouse-binary-path ${{ env.clickhouse_binary_path }}  
              --clickhouse-version ${{ env.version }} 
              --attr project="$GITHUB_REPOSITORY" project.id="$GITHUB_REPOSITORY_ID" user.name="$GITHUB_ACTOR" version="${{ inputs.version }}" package="${{ inputs.package }}" repository="https://github.com/Altinity/clickhouse-regression" commit.hash="$GITHUB_SHA" job.id="$GITHUB_RUN_ID" job.url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" arch="${{ vars.ARCH }}"
              --log raw.log

      - name: Create and upload logs
        if: success() || failure()
        run: .github/manage_logs.sh ${{ vars.UPLOAD_LOGS }}

      - name: Debug pause
        if: ${{ vars.PAUSE == 1 }}
        run: |
          echo "...debugging mode...sleeping 6 hours..."
          sleep 21600

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.SUITE }}-artifacts
          path: |
            ./report.html
            ./*.log.txt
            ./*.log
            ./*.html
            ./*/_instances/*/logs/*.log
            ./*/*/_instances/*/logs/*.log
            ./*/_instances/*.log
            ./*/*/_instances/*.log

  example:
    runs-on: self-hosted
    env:
      SUITE: example
    if: ${{ inputs.suite == 'all' || inputs.suite == SUITE }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: .github/setup.sh

      - name: Run ${{ env.SUITE }} suite
        run: python3 
              -u ${{ env.SUITE }}/regression.py
              --test-to-end
              --local
              --collect-service-logs 
              --output ${{ vars.OUTPUT }} 
              --parallel ${{ vars.PARALLEL }}
              --clickhouse-binary-path ${{ env.clickhouse_binary_path }}  
              --clickhouse-version ${{ env.version }} 
              --attr project="$GITHUB_REPOSITORY" project.id="$GITHUB_REPOSITORY_ID" user.name="$GITHUB_ACTOR" version="${{ inputs.version }}" package="${{ inputs.package }}" repository="https://github.com/Altinity/clickhouse-regression" commit.hash="$GITHUB_SHA" job.id="$GITHUB_RUN_ID" job.url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" arch="${{ vars.ARCH }}"
              --log raw.log

      - name: Create and upload logs
        if: success() || failure()
        run: .github/manage_logs.sh ${{ vars.UPLOAD_LOGS }}

      - name: Debug pause
        if: ${{ vars.PAUSE == 1 }}
        run: |
          echo "...debugging mode...sleeping 6 hours..."
          sleep 21600

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.SUITE }}-artifacts
          path: |
            ./report.html
            ./*.log.txt
            ./*.log
            ./*.html
            ./*/_instances/*/logs/*.log
            ./*/*/_instances/*/logs/*.log
            ./*/_instances/*.log
            ./*/*/_instances/*.log
