name: Start GitLab CI/CD regression run
run-name: ${{ github.actor }} is running regression tests
on: 
  workflow_dispatch:
    inputs:
      package:
        description: "Package either 'docker://' or 'https://'. Example: 'https://s3.amazonaws.com/clickhouse-builds/23.3/.../package_release/clickhouse-common-static_23.3.1.64_amd64.deb', or 'docker://clickhouse/clickhouse-server:22.11.6-alpine'"
        required: true
        type: string
      version:
        description: "Expected version. Example: 23.3.1.64"
        required: true
        type: string
      suite:
        description: "Test suite to run (default: all)"
        type: choice
        options:
          - all
          - aes_encryption
          - aggregate_functions
          - atomic_insert
          - base_58
          - clickhouse_keeper
          - datetime64_extended_range
          - disk_level_encryption
          - dns
          - example
          - extended_precision_data_types
          - functional
          - kafka
          - kerberos
          - ldap
          - lightweight_delete
          - map_type
          - parquet
          - part_moves_between_shards
          - rbac
          - s3
          - s3_aws
          - s3_gcs
          - selects
          - ssl_server
          - tiered_storage
          - tiered_storage_aws
          - tiered_storage_gcs
          - window_functions
          - benchmark
      artifacts:
        description: "Artifact S3 bucket"
        type: choice
        options:
          - internal
          - public

jobs:
  regression:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [
          aes_encryption,
          aggregate_functions,
          atomic_insert,
          base_58,
          clickhouse_keeper,
          datetime64_extended_range,
          disk_level_encryption,
          dns,
          example,
          extended_precision_data_types,
          functional,
          kafka,
          kerberos,
          ldap,
          lightweight_delete,
          map_type,
          parquet,
          part_moves_between_shards,
          rbac,
          s3,
          s3_aws,
          s3_gcs,
          selects,
          ssl_server,
          tiered_storage,
          tiered_storage_aws,
          tiered_storage_gcs,
          window_functions,
          benchmark
          ]
    if: contains(${{ inputs.suite }}, ['all', ${{ matrix.suite }}])
    name: ${{ matrix.suite }}
    steps:
      - uses: actions/checkout@v3
      - run: pip install python-gitlab
      - run: ./cicd-trigger.py --package ${{ inputs.package }} --version ${{ inputs.version }} --suite ${{ matrix.suite }} --token ${{ secrets.GL_PIPELINE_TOKEN }} --artifacts ${{ inputs.artifacts }} --wait
