name: Run scheduled CI/CD regression tests
run-name: Scheduled Regression
on:
  workflow_dispatch:
    inputs:
      suite:
        type: string
        description: "Test suite to run. Default: all"
        default: all
      artifacts:
        description: "Artifact S3 bucket"
        type: string
        default: public
      output_format:
        description: "Testflows output style."
        type: string
        default: new-fails
      ref:
        description: "Commit SHA to checkout. Default: current (empty string)."
        type: string
        default: ""
      extra_args:
        description: "Extra test program arguments. Default: none (empty string)."
        type: string
        default: ""
  schedule:
    - cron: "0 0 * * *"

jobs:
  altinitystable-23-8-11-29:
    uses: ./.github/workflows/test-reusable-workflow.yml
    with:
      package: docker://altinity/clickhouse-server:23.8.11.29.altinitystable
      version: '23.8.11.29'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REPORT_REGION: ${{ secrets.AWS_REPORT_REGION }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      GCS_URI: ${{ secrets.GCS_URI }}
      GCS_KEY_ID: ${{ secrets.GCS_KEY_ID }}
      GCS_KEY_SECRET: ${{ secrets.GCS_KEY_SECRET }}
  altinitystable-23-3-19-33:
    uses: ./.github/workflows/test-reusable-workflow.yml
    with:
      package: docker://altinity/clickhouse-server:23.3.19.33.altinitystable
      version: '23.3.19.33'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REPORT_REGION: ${{ secrets.AWS_REPORT_REGION }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      GCS_URI: ${{ secrets.GCS_URI }}
      GCS_KEY_ID: ${{ secrets.GCS_KEY_ID }}
      GCS_KEY_SECRET: ${{ secrets.GCS_KEY_SECRET }}
  altinitystable-22-8-15-25:
    uses: ./.github/workflows/test-reusable-workflow.yml
    with:
      package: docker://altinity/clickhouse-server:22.8.15.25.altinitystable
      version: '22.8.15.25'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REPORT_REGION: ${{ secrets.AWS_REPORT_REGION }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      GCS_URI: ${{ secrets.GCS_URI }}
      GCS_KEY_ID: ${{ secrets.GCS_KEY_ID }}
      GCS_KEY_SECRET: ${{ secrets.GCS_KEY_SECRET }}
  clickhouse-24-4:
    uses: ./.github/workflows/test-reusable-workflow.yml
    with:
      package: docker://clickhouse/clickhouse-server:24.4
      version: '24.4'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REPORT_REGION: ${{ secrets.AWS_REPORT_REGION }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      GCS_URI: ${{ secrets.GCS_URI }}
      GCS_KEY_ID: ${{ secrets.GCS_KEY_ID }}
      GCS_KEY_SECRET: ${{ secrets.GCS_KEY_SECRET }}
  clickhouse-24-3:
    uses: ./.github/workflows/test-reusable-workflow.yml
    with:
      package: docker://clickhouse/clickhouse-server:24.3
      version: '24.3'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REPORT_REGION: ${{ secrets.AWS_REPORT_REGION }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      GCS_URI: ${{ secrets.GCS_URI }}
      GCS_KEY_ID: ${{ secrets.GCS_KEY_ID }}
      GCS_KEY_SECRET: ${{ secrets.GCS_KEY_SECRET }}