name: 🗓 Scheduled Altinity 24.8
run-name: 🗓 Scheduled Altinity 24.8
on:
  workflow_dispatch:
  #Run at 00:00 AM (UTC) on Sunday
  schedule:
    - cron: "0 0 * * 6"

jobs:
  altinitystable-24-8-x86-with-analyzer-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://altinity/clickhouse-server:24.8.11.51285.altinitystable
      version: '24.8.11.51285'
      extra_args: '--with-analyzer'
      arch: x86
    secrets: inherit

  altinitystable-24-8-arm-with-analyzer-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://altinity/clickhouse-server:24.8.11.51285.altinitystable
      version: '24.8.11.51285'
      extra_args: '--with-analyzer'
      arch: arm64
    secrets: inherit
