name: 🗓 Scheduled ClickHouse 23.3
run-name: 🗓 Scheduled ClickHouse 23.3
on:
  workflow_dispatch:
  #Run at 00:00 AM (UTC) on Sunday
  schedule:
    - cron: "0 0 * * 6"

jobs:
  clickhouse-23-3-x86-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://clickhouse/clickhouse-server:23.3.22.3-alpine
      version: '23.3.22.3'
      arch: x86
    secrets: inherit

  clickhouse-23-3-arm-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://clickhouse/clickhouse-server:23.3.22.3-alpine
      version: '23.3.22.3'
      arch: arm64
    secrets: inherit
