name: Scheduled Altinity 23.8 Regression
run-name: Scheduled Altinity 23.8 Regression
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  altinitystable-23-8-x86:
    uses: ./.github/workflows/reusable-workflow-x86.yml
    with:
      package: docker://altinity/clickhouse-server:23.8.11.29.altinitystable
      version: '23.8.11.29'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_REPORT_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_REPORT_SECRET_ACCESS_KEY }}
      AWS_REPORT_REGION: ${{ secrets.AWS_REPORT_REGION }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      GCS_URI: ${{ secrets.GCS_URI }}
      GCS_KEY_ID: ${{ secrets.GCS_KEY_ID }}
      GCS_KEY_SECRET: ${{ secrets.GCS_KEY_SECRET }}
  altinitystable-23-8-arm:
    uses: ./.github/workflows/reusable-workflow-arm.yml
    with:
      package: docker://altinity/clickhouse-server:23.8.11.29.altinitystable
      version: '23.8.11.29'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_REPORT_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_REPORT_SECRET_ACCESS_KEY }}
      AWS_REPORT_REGION: ${{ secrets.AWS_REPORT_REGION }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      GCS_URI: ${{ secrets.GCS_URI }}
      GCS_KEY_ID: ${{ secrets.GCS_KEY_ID }}
      GCS_KEY_SECRET: ${{ secrets.GCS_KEY_SECRET }}