name: 🗓 Scheduled Altinity 23.8
run-name: 🗓 Scheduled Altinity 23.8
on:
  workflow_dispatch:
  #Run at 00:00 AM (UTC) on Sunday
  schedule:
    - cron: "0 0 * * 6"

jobs:
  altinitystable-23-8-x86-zookeeper:
    uses: ./.github/workflows/reusable-workflow-x86.yml
    with:
      package: docker://altinity/clickhouse-server:23.8.16.43.altinitystable
      version: '23.8.16.43'
      artifact_name: altinitystable-23-8-x86-zookeeper
    secrets: inherit

  altinitystable-23-8-arm-zookeeper:
    uses: ./.github/workflows/reusable-workflow-arm.yml
    with:
      package: docker://altinity/clickhouse-server:23.8.16.43.altinitystable
      version: '23.8.16.43'
      artifact_name: altinitystable-23-8-arm-zookeeper
    secrets: inherit
