name: 🗓 Scheduled Altinity 25.2 Antalya 
run-name: 🗓 Scheduled Altinity 25.2 Antalya 
on:
  workflow_dispatch:
  #Run at 00:00 AM (UTC) on Sunday
  schedule:
    - cron: "0 0 * * 6"

jobs:
  altinitystable-25-2-antalya-x86-with-analyzer-zookeeper:
    uses: ./.github/workflows/run-reusable-regression.yml
    with:
      package: docker://altinity/clickhouse-server:25.2.2.28788.altinityantalya
      version: '25.2.2.28788'
      extra_args: '--with-analyzer'
      run_s3_suites: true
      arch: x86
    secrets: inherit

  altinitystable-25-2-antalya-arm-with-analyzer-zookeeper:
    uses: ./.github/workflows/run-reusable-regression.yml
    with:
      package: docker://altinity/clickhouse-server:25.2.2.28788.altinityantalya
      version: '25.2.2.28788'
      extra_args: '--with-analyzer'
      run_s3_suites: true
      arch: arm64
    secrets: inherit
