name: 🗓 Scheduled Altinity 23.8
run-name: 🗓 Scheduled Altinity 23.8
on:
  workflow_dispatch:
  #Run at 00:00 AM (UTC) on Sunday
  schedule:
    - cron: "0 0 * * 6"

jobs:
  altinitystable-23-8-x86-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://altinity/clickhouse-server:23.8.16.43.altinitystable
      version: '23.8.16.43'
      arch: x86
    secrets: inherit

  altinitystable-23-8-arm-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://altinity/clickhouse-server:23.8.16.43.altinitystable
      version: '23.8.16.43'
      arch: arm64
    secrets: inherit
