name: Scheduled ClickHouse 23.8
run-name: Scheduled ClickHouse 23.8
on:
  workflow_dispatch:
  #Run at 00:00 AM (UTC) on Sunday
  schedule:
    - cron: "0 0 * * 6"

jobs:
  clickhouse-23-8-x86-zookeeper:
    uses: ./.github/workflows/reusable-workflow-x86.yml
    with:
      package: docker://clickhouse/clickhouse-server:23.8.16.16-alpine
      version: '23.8.16.16'
      artifact_name: clickhouse-23-8-x86-zookeeper
    secrets: inherit

  clickhouse-23-8-arm-zookeeper:
    uses: ./.github/workflows/reusable-workflow-arm.yml
    with:
      package: docker://clickhouse/clickhouse-server:23.8.16.16-alpine
      version: '23.8.16.16'
      artifact_name: clickhouse-23-8-arm-zookeeper
    secrets: inherit
