name: 🗓 Scheduled ClickHouse 23.8
run-name: 🗓 Scheduled ClickHouse 23.8
on:
  workflow_dispatch:
  #Run at 10:00 PM (UTC) on Sunday
  schedule:
    - cron: "0 22 * * 0"

jobs:
  clickhouse-23-8-x86-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://clickhouse/clickhouse-server:23.8.16.16-alpine
      version: '23.8.16.16'
      arch: x86
    secrets: inherit

  clickhouse-23-8-arm-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://clickhouse/clickhouse-server:23.8.16.16-alpine
      version: '23.8.16.16'
      arch: arm64
    secrets: inherit
