name: 🗓 Scheduled Altinity 22.3
run-name: 🗓 Scheduled Altinity 22.3
on:
  workflow_dispatch:
  #Run at 10:00 PM (UTC) on Friday
  schedule:
    - cron: "0 22 * * 5"

jobs:
  altinitystable-22-3-x86-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://altinity/clickhouse-server:22.3.15.34.altinitystable
      version: '22.3.15.34'
      arch: x86
    secrets: inherit
