name: 🗓 Scheduled Altinity 25.3 Antalya 
run-name: 🗓 Scheduled Altinity 25.3 Antalya 
on:
  workflow_dispatch:
  #Run at 10:00 PM (UTC) on Saturday
  schedule:
    - cron: "0 22 * * 6"

jobs:
  altinitystable-25-3-antalya-x86-with-analyzer-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://altinity/clickhouse-server:25.3.3.20143.altinityantalya
      version: '25.3.3.20143'
      extra_args: '--with-analyzer'
      run_s3_suites: true
      arch: x86
    secrets: inherit

#  altinitystable-25-3-antalya-arm-with-analyzer-zookeeper:
#    uses: ./.github/workflows/run-regression.yml
#    with:
#      package: docker://altinity/clickhouse-server:25.3.3.20143.altinityantalya
#      version: '25.3.3.20143'
#      extra_args: '--with-analyzer'
#      run_s3_suites: true
#      arch: arm64
#    secrets: inherit
