name: 🗓 Scheduled Altinity 24.12-Antalya
run-name: 🗓 Scheduled Altinity 24.12-Antalya
on:
  workflow_dispatch:
  #Run at 00:00 AM (UTC) on Sunday
  schedule:
    - cron: "0 0 * * 6"

jobs:
  altinitystable-24-12-antalya-x86-with-analyzer-zookeeper:
    uses: ./.github/workflows/reusable-workflow-x86.yml
    with:
      package: docker://altinity/clickhouse-server:24.12.2.20203.altinityantalya
      version: '24.12.2.20203'
      extra_args: '--with-analyzer'
      artifact_name: altinityedge-24-12-antalya-x86-with-analyzer-zookeeper
      run_s3_suites: true
    secrets: inherit

  altinitystable-24-12-antalya-arm-with-analyzer-zookeeper:
    uses: ./.github/workflows/reusable-workflow-arm.yml
    with:
      package: docker://altinity/clickhouse-server:24.12.2.20203.altinityantalya
      version: '24.12.2.20203'
      extra_args: '--with-analyzer'
      artifact_name: altinityedge-24-12-antalya-arm-with-analyzer-zookeeper
      run_s3_suites: true
    secrets: inherit
