name: Scheduled Altinity 22.3
run-name: Scheduled Altinity 22.3
on:
  workflow_dispatch:
  #Run at 12:00 AM (UTC), Monday through Thursday
  schedule:
    - cron: "0 0 * * 1-5"

jobs:
  altinitystable-22-3-x86-zookeeper:
    uses: ./.github/workflows/reusable-workflow-x86.yml
    with:
      package: docker://altinity/clickhouse-server:22.3.15.34.altinitystable
      version: '22.3.15.34'
      artifact_name: altinitystable-22-3-x86-zookeeper
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_REPORT_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_REPORT_SECRET_ACCESS_KEY }}
      AWS_REPORT_REGION: ${{ secrets.AWS_REPORT_REGION }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      # AWS_REGION: ${{ secrets.AWS_REGION }}
      # AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      # AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      # GCS_URI: ${{ secrets.GCS_URI }}
      # GCS_KEY_ID: ${{ secrets.GCS_KEY_ID }}
      # GCS_KEY_SECRET: ${{ secrets.GCS_KEY_SECRET }}
      CHECKS_DATABASE_HOST: ${{ secrets.CHECKS_DATABASE_HOST }}
      CHECKS_DATABASE_USER: ${{ secrets.CHECKS_DATABASE_USER }}
      CHECKS_DATABASE_PASSWORD: ${{ secrets.CHECKS_DATABASE_PASSWORD }}
