name: 🗓 Scheduled Altinity 22.8
run-name: 🗓 Scheduled Altinity 22.8
on:
  workflow_dispatch:
  #Run at 00:00 AM (UTC) on Sunday
  schedule:
    - cron: "0 0 * * 6"

jobs:
  altinitystable-22-8-x86-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://altinity/clickhouse-server:22.8.15.25.altinitystable
      version: '22.8.15.25'
      arch: x86
    secrets: inherit

  altinitystable-22-8-arm-zookeeper:
    uses: ./.github/workflows/run-regression.yml
    with:
      package: docker://altinity/clickhouse-server:22.8.15.25.altinitystable
      version: '22.8.15.25'
      arch: arm64
    secrets: inherit
