name: Scheduled Altinity 22.3
run-name: Scheduled Altinity 22.3
on:
  workflow_dispatch:
  #Run at 00:00 AM (UTC) on Sunday
  schedule:
    - cron: "0 0 * * 6"

jobs:
  altinitystable-22-3-x86-zookeeper:
    uses: ./.github/workflows/reusable-workflow-x86.yml
    with:
      package: docker://altinity/clickhouse-server:22.3.15.34.altinitystable
      version: '22.3.15.34'
      artifact_name: altinitystable-22-3-x86-zookeeper
    secrets: inherit
