name: Test Daily Scheduled Regression
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scheduled-regression-test:
    uses: ./.github/workflows/test-reusable-workflow.yml
    with:
      package: docker://altinity/clickhouse-server:23.8.5.17.altinitytest
      version: 23.8.5.17.altinitytest
      suite: all
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REPORT_REGION }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REPORT_REGION }}
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      GCS_URI: ${{ secrets.GCS_URI }}
      GCS_KEY_ID: ${{ secrets.GCS_KEY_ID }}
      GCS_KEY_SECRET: ${{ secrets.GCS_KEY_SECRET }}